include: package:lints/recommended.yaml

analyzer:
  errors:
    dead_code: error
    unused_element: error
    unused_import: error
    unused_local_variable: error
    todo: ignore

linter:
  rules:
    always_declare_return_types: true
    await_only_futures: true
    hash_and_equals: true
    implementation_imports: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
