name: rpi_gpio
version: 0.10.0
description: rpi_gpio is a Dart library for accessing the Raspberry Pi GPIO pins.
homepage: https://github.com/danrubel/rpi_gpio.dart

# This package only works with Linux running on Raspberry Pi
platforms:
  linux:
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  ffi: ^2.1.2
  path: ^1.8.0
dev_dependencies:
  grinder: ^0.9.0
  lints: ^4.0.0
  test: ^1.17.9
